/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    basic: Basic;
    event: Event;
    carouselSlide: CarouselSlide;
    bannerLinks: BannerLink;
    boardMembers: BoardMember;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    basic: BasicSelect<false> | BasicSelect<true>;
    event: EventSelect<false> | EventSelect<true>;
    carouselSlide: CarouselSlideSelect<false> | CarouselSlideSelect<true>;
    bannerLinks: BannerLinksSelect<false> | BannerLinksSelect<true>;
    boardMembers: BoardMembersSelect<false> | BoardMembersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "basic".
 */
export interface Basic {
  id: number;
  Name: string;
  Location: string;
  Quarter?: ('Fall' | 'Winter' | 'Spring') | null;
  Day?: ('Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday' | 'Saturday' | 'Sunday') | null;
  Time: string;
  bgImage: number | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event".
 */
export interface Event {
  id: number;
  Name: string;
  'Week 1'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 2'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 3'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 4'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 5'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 6'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 7'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 8'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 9'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  'Week 10'?: {
    Thursday?: string | null;
    Saturday?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Each document is one slide in the hero carousel.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carouselSlide".
 */
export interface CarouselSlide {
  id: number;
  name: string;
  visible?: boolean | null;
  bgImage: number | Media;
  type:
    | 'default'
    | 'image-only'
    | 'image-text-card'
    | 'image-text-card-bottom'
    | 'image-text-link'
    | 'image-text-card-button';
  /**
   * Controls the maximum width of the overlay card.
   */
  width?: ('max-w-xs' | 'max-w-sm' | 'max-w-md' | 'max-w-lg' | 'max-w-xl') | null;
  /**
   * Main heading shown on the card overlay.
   */
  text?: string | null;
  description?: string | null;
  description2?: string | null;
  /**
   * Full URL the button should open (opens in a new tab).
   */
  link?: string | null;
  buttonText?: string | null;
  /**
   * Each row becomes one line of the large stacked title.
   */
  title?:
    | {
        line: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Smaller text appended to the last title line (e.g. "@ UCLA").
   */
  subtitle?: string | null;
  /**
   * Icon + text rows shown below the title (time, location, etc.).
   */
  details?:
    | {
        icon: 'clock' | 'location' | 'calendar' | 'users' | 'message' | 'mail';
        text: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bannerLinks".
 */
export interface BannerLink {
  id: number;
  Link: string;
  Text: string;
  visible: boolean;
  'Icon Type'?: ('form-icon' | 'game-icon') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardMembers".
 */
export interface BoardMember {
  id: number;
  'Member Name': string;
  Role?:
    | (
        | 'President'
        | 'Vice President'
        | 'EVP'
        | 'Screener'
        | 'Webmaster'
        | 'Stashmaster'
        | 'Treasurer'
        | 'Secretary'
        | 'Discord Manager'
        | 'General Officer'
      )
    | null;
  Year?: ('Freshman' | 'Sophomore' | 'Junior' | 'Senior') | null;
  Major: string;
  Picture: number | Media;
  BackgroundImage?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'basic';
        value: number | Basic;
      } | null)
    | ({
        relationTo: 'event';
        value: number | Event;
      } | null)
    | ({
        relationTo: 'carouselSlide';
        value: number | CarouselSlide;
      } | null)
    | ({
        relationTo: 'bannerLinks';
        value: number | BannerLink;
      } | null)
    | ({
        relationTo: 'boardMembers';
        value: number | BoardMember;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "basic_select".
 */
export interface BasicSelect<T extends boolean = true> {
  Name?: T;
  Location?: T;
  Quarter?: T;
  Day?: T;
  Time?: T;
  bgImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "event_select".
 */
export interface EventSelect<T extends boolean = true> {
  Name?: T;
  'Week 1'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 2'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 3'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 4'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 5'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 6'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 7'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 8'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 9'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  'Week 10'?:
    | T
    | {
        Thursday?: T;
        Saturday?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "carouselSlide_select".
 */
export interface CarouselSlideSelect<T extends boolean = true> {
  name?: T;
  visible?: T;
  bgImage?: T;
  type?: T;
  width?: T;
  text?: T;
  description?: T;
  description2?: T;
  link?: T;
  buttonText?: T;
  title?:
    | T
    | {
        line?: T;
        id?: T;
      };
  subtitle?: T;
  details?:
    | T
    | {
        icon?: T;
        text?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bannerLinks_select".
 */
export interface BannerLinksSelect<T extends boolean = true> {
  Link?: T;
  Text?: T;
  visible?: T;
  'Icon Type'?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "boardMembers_select".
 */
export interface BoardMembersSelect<T extends boolean = true> {
  'Member Name'?: T;
  Role?: T;
  Year?: T;
  Major?: T;
  Picture?: T;
  BackgroundImage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}